white-space = ? white space characters ? , { ? white space characters ? } ;
any = ? all visible characters ? ;

letter = "A" | "B" | "C" | "D" | "E" | "F" | "G"
       | "H" | "I" | "J" | "K" | "L" | "M" | "N"
       | "O" | "P" | "Q" | "R" | "S" | "T" | "U"
       | "V" | "W" | "X" | "Y" | "Z" | "a" | "b"
       | "c" | "d" | "e" | "f" | "g" | "h" | "i"
       | "j" | "k" | "l" | "m" | "n" | "o" | "p"
       | "q" | "r" | "s" | "t" | "u" | "v" | "w"
       | "x" | "y" | "z" ;

digit-base-2  = "0" | "1";
digit-base-8  = "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7";
digit-base-10 = "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9" ;
digit-base-16 = "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9" 
              | "A" | "B" | "C" | "D" | "E" | "F" | "a" | "b" | "c" | "d"
              | "e" | "f" ;

number-base-2  = "0b" | "0B", { digit-base-2  | "_" } ;
number-base-8  = "0o" | "0O", { digit-base-8  | "_" } ;
number-base-16 = "0x" | "0X", { digit-base-16 | "_" } ;
number-base-10 = digit-base-10 , { digit-base-10 } , [ "." , digit-base-10 , { digit-base-10 } ] ;
number         = number-base-2 | number-base-8 | number-base-10 | number-base-16 ;

shebang = "#!" , { any - "\n" } ;

comment = "//" , { any - "\n" } ;

character-part = any - ( '"' | "\n" )
               | "\x" , digit-base-16 , { digit-base-16 }
               | "\\" , any
               ;

character-lit = "'" , character-part , "'" ;

string-lit = '"' , { character-part } , '"' ;

identifier = letter | "_" , { letter | "_" | digit-base-10 } ;

qualifier = "const" | "var" | "comptime" | "runtime" | "static";
qualifiers = qualifier , { [ white-space ] , qualifier } ;

expression = expression-qualified
           | expression-tuple
           | expression-prefix
           | expression-binary
           | "true"
           | "false"
           | "nothing"
           | number
           | character-lit
           | string-lit
           | identifier
           | expression-func
           | expression-tuple
           | expression , [ white-space ] , '(' , [ white-space ] , [ init-fields ] , [ white-space ] , ')'
           | "use" , [ white-space ] , statement-block
           ;

expression-tuple = '(' , [ white-space ] , [ expression , { [ white-space ] , ',' , [ white-space ] , expression } ] , [ white-space ] ,  ')' ;

init-field = [ expression , [ white-space ] , '=' , [ white-space ] ] , expression ;
init-fields = init-field , { [ white-space ] , ',' , [ white-space ] , init-field } ;

expression-init = expression , [ white-space ] , '{' , [ white-space ] , [ init-fields ] , [ white-space ] , '}' ;

expression-qualified = qualifiers , [ white-space ] , expression ;

expression-tuple = '(' , [ white-space ] , expression , [ white-space ] , ')' ;

expression-prefix = (
                        "~" | "?" | "+" | "-" | "*" | "&" | "..." | "not" |
                        '[' , [ white-space ] , [ expression ] , [ white-space ] , ']'
                    ) ,
                    [ white-space ] ,
                    expression
                    ;

expression-binary = expression ,
                    [ white-space ] ,
                      "+"  | "-"  | "%" | "/" | "*"  | "^"  | "&"  | "|"
                    | "<<" | ">>" | "<" | ">" | "<=" | ">=" | "==" | "!="
                    | ".." | "."
                    ,
                    [ white-space ] ,
                    expression
                    ;

func-param = identifier , [ white-space ] , ":" , [ white-space ] , expression ,
             [ [ white-space ] , "=" , [ white-space ] , expression ]
             ;

func-params = '(' , [ white-space ] , [ func-param , {"," , [ white-space ] , func-param } ]  , [ white-space ] , ')' ;

expression-func = "func" , [ white-space ] , func-params , [ white-space ] , statement-block ;

statement = statement-block
          | qualifiers , white-space , expression , [ [ white-space ] , ':' , [ white-space ] , expression , [ white-space ] ] , [ [ white-space ] , "=" , [ white-space ] , expression ]
          | qualifier , [ white-space ] , statement
          | expression
          | "return"
          | "break"
          | "continue"
          | "if" , [ white-space ] , expression , [ white-space ] , statement-block
          | "for" , [ white-space ] ,
            [ [ expression ] , [ white-space ] , ';' , [white-space] ] ,
            [ expression ] ,
            [ [white-space] , ';' , [ white-space ] , [ expression ] ] , [ white-space ] ,
            statement-block
          ;

statement-block = '{' , { statement } , '}' ;